# Site
name: "Marketing Strategy Planning Guide"
title: "Online Marketing - SEO, SEM, SMO and More "
description: "Find strategic marketing techniques and online marketing tools for small businesses. Discover tips for SEO, SEM SMM, research and more. Grow your company today!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 'https://marketingstrategyplan.org'
google_analytics: 'G-YKCBMGZ8LQ'
disqus: 'afGZDYYvBY'
mailchimp-list: 'https://mailchi.mp/9b768e7e0ee1/marketintg'
include: ["_pages"]
permalink: /blog/:title/

# Authors
authors:
  dejuan:
    name: dejaun
    display_name: Dejuan
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: jonesdejuan24@gmail.com
    web: https://www.linkedin.com/company/marketing-strategy-plan
    twitter: https://twitter.com/moneyonline_fre
    description: "Author of Marketingstrategyplan."
  john:
    name: john
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: jonesdejuan24@gmail.com
    web: https://www.linkedin.com/company/marketing-strategy-plan
    twitter: https://twitter.com/moneyonline_fre
    description: "One of many authors at marketingstrategyplan."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-9965740454699088"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
